In [257]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [258]:
from src.pnn.layer.input_layer import InputLayer
from src.pnn.tensor import Tensor
from src.pnn.layer.fully_connected import FullyConnected
from src.pnn.layer.activation import ActivationLayer, sigmoid, soft_max
import mnist
import numpy as np 

In [259]:
images = mnist.train_images()

# Input Layer

In [260]:
input_layer = InputLayer()
input_tensorlist = input_layer.forward(images)

# Fully Connected 1

In [261]:
out_shape=(100,)
fully_connected = FullyConnected(in_shape=input_tensorlist[0].shape, out_shape=out_shape)
out_tensor_fully_connected1 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=input_tensorlist, out_tensors=out_tensor_fully_connected1)

In [262]:
out_tensor_fully_connected1[0].elements

array([13985.34681376, 15433.37721785, 14036.9359551 , 14682.37928788,
       13881.02226995, 13805.77030836, 14207.34011567, 14933.54540184,
       14072.96791034, 12676.56564302, 14065.02167984, 13492.22710132,
       15500.10443432, 13165.00646062, 13162.52610039, 13451.73318427,
       14249.38035717, 14005.35156749, 13085.58245089, 13769.95038232,
       14132.26552887, 12526.43353163, 13352.59049995, 14135.15130902,
       14533.62173864, 13372.08116108, 13373.23008524, 13518.38409165,
       12790.48371815, 13697.12515216, 15254.45626241, 13754.56413947,
       14104.47967533, 13939.53657155, 12791.92857373, 12590.38365112,
       12750.89785673, 13488.66873161, 14032.10091735, 13444.86214618,
       14472.22913673, 13556.6897942 , 14610.28798921, 13409.87854507,
       14533.73693975, 13267.41801144, 14307.39126307, 15170.3576435 ,
       15456.81929514, 13881.56000484, 14009.36983064, 14108.74076745,
       13195.3819744 , 14677.53405458, 14487.15940767, 14032.46826074,
      

# Sigmoid

In [263]:
activation_layer = ActivationLayer(sigmoid)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected1, out_tensor_activation)

In [264]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[1].elements

100


array([0.76211768, 0.29731393, 0.5080642 , 0.45694143, 0.24476307,
       0.99917545, 0.45865949, 0.62172213, 0.88466208, 0.43287041,
       0.99961966, 0.59142824, 0.70520989, 0.76589825, 0.25217722,
       0.26506689, 0.20602895, 0.97064439, 0.86743356, 0.60669963,
       0.77854996, 0.93740168, 0.98676421, 0.30833479, 0.2048915 ,
       0.34451054, 0.44478511, 0.59728171, 0.85831245, 0.4942477 ,
       0.47438563, 0.46594741, 0.12432916, 0.14384993, 0.37125498,
       0.89204765, 0.5378683 , 0.93666892, 0.18856572, 0.34082857,
       0.40899724, 0.10013759, 0.66599096, 0.66979194, 0.40567498,
       0.77743366, 0.15120794, 0.54361305, 0.4601784 , 0.68640034,
       0.26743706, 0.88490161, 0.61078831, 0.21053765, 0.82233236,
       0.93963011, 0.98744397, 0.85691449, 0.46738452, 0.54459941,
       0.32963993, 0.04100199, 0.10138405, 0.52854873, 0.21450109,
       0.961019  , 0.02034125, 0.27259525, 0.5068632 , 0.85500679,
       0.35955038, 0.87138939, 0.58950733, 0.40479484, 0.03929

# Fully Connected 2

In [265]:
out_shape=(10,)
fully_connected = FullyConnected(in_shape=out_tensor_activation[0].shape, out_shape=out_shape)
out_tensor_fully_connected2 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=out_tensor_activation, out_tensors=out_tensor_fully_connected2)

In [266]:
out_tensor_fully_connected2[0].elements

array([30.27711425, 27.08922536, 30.55297041, 29.02768508, 28.00148764,
       29.20370053, 27.50276268, 27.74427665, 27.56540434, 27.99268665])

# Soft Max

In [270]:
#summe = [np.exp(x_j) for x_j in out_tensor_fully_connected2[0].elements]
summe = np.sum(np.exp(out_tensor_fully_connected2[0].elements))
summe

47939417776693.24

In [271]:
activation_layer = ActivationLayer(soft_max)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected2, out_tensor_activation)

In [272]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[1].elements

10


array([0.05072468, 0.43462817, 0.0933926 , 0.81252622, 0.24052589,
       0.54553947, 0.71615271, 0.07569898, 0.82455171, 0.19100011])