In [9]:
%load_ext autoreload
%autoreload 2

In [48]:
from src.pnn.layer.input_layer import InputLayer
from src.pnn.tensor import Tensor
from src.pnn.layer.fully_connected import FullyConnected
import mnist
import numpy as np 

In [103]:
images = mnist.train_images()

In [104]:
images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [105]:
input_layer = InputLayer()
tensorlist = input_layer.forward(images)

In [106]:
bias = np.array([0 for i in range(0,100)])
# length bias * length inputelement
weightmatrix = Tensor(np.array([[0 for i in range(0, len(bias))] 
                         for j in range(0, len(tensorlist[0].elements))]), None)
# length bias * length list of inputs
out_tensors = np.array([Tensor([0 for i in range(0, len(bias))], None) 
                        for j in range(0, len(tensorlist))])
bias = np.array([0 for i in range(0,100)])

In [107]:
print(len(tensorlist[0].elements)==len(weightmatrix.elements))
print(len(tensorlist)==len(out_tensors))
print(len(weightmatrix.elements[0])==len(bias))

True
True
True


In [108]:
fully_connected = FullyConnected(bias=bias, weightmatrix=weightmatrix)

In [111]:
fully_connected.forward(in_tensors=tensorlist, out_tensors=out_tensors)

In [85]:
arr1 = np.ndarray(shape=(3, 2))
arr2 = np.array([1,1,1])

In [95]:
arr2 * arr1.transpose() 

array([[3.47739925e-081, 1.13109158e-042, 4.04570958e-057],
       [1.20032327e-071, 8.84342613e+165, 3.59410673e-317]])

In [29]:
tensorlist[0].elements

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17