In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from pnn.layer.input import InputLayer
from pnn.tensor import Tensor
from pnn.layer.fully_connected import FullyConnected
from pnn.layer.activation import ActivationLayer, sigmoid, soft_max
from pnn.layer.loss import LossLayer, mean_squared_error, cross_entropy
from pnn.network import Network
from pnn.trainer import Trainer, sgd
from pnn.shape import Shape
import mnist
import numpy as np 

# Items

In [2]:
mnist.temporary_dir = lambda: './data'
train_images = mnist.train_images()
train_images = np.divide(train_images, np.max(train_images))
train_labels = mnist.train_labels()

test_images = mnist.test_images()
test_images = np.divide(test_images, np.max(test_images))
test_labels = mnist.test_labels()

# train_images = train_images[5:5000]
# train_labels = train_labels[5:5000]
# train_labels = np.array(train_labels)

# Trainer

In [14]:
# fully_connected_1 = FullyConnected(out_shape=Shape((784,)), initialization_technique='sigmoid')
# activation_layer_sigmoid1 = ActivationLayer(sigmoid)
fully_connected_2 = FullyConnected(out_shape=Shape((196,)), initialization_technique='sigmoid')
activation_layer_sigmoid2 = ActivationLayer(sigmoid)
fully_connected_3 = FullyConnected(out_shape=Shape((49,)), initialization_technique='sigmoid')
activation_layer_sigmoid3 = ActivationLayer(sigmoid)
fully_connected_4 = FullyConnected(out_shape=Shape((10,)), initialization_technique='softmax') 
activation_layer_soft_max = ActivationLayer(soft_max)
loss_layer = LossLayer(mean_squared_error)
layerlist = [#fully_connected_1, activation_layer_sigmoid1, 
             fully_connected_2, activation_layer_sigmoid2,
             fully_connected_3, activation_layer_sigmoid3,
             fully_connected_4, activation_layer_soft_max, loss_layer]
network = Network(layerlist)

sgd_trainer = Trainer(
    learning_rate=0.03,
    amount_epochs=10,
    update_mechanism=sgd,
    batch_size=1)

In [15]:
sgd_trainer.optimize(network=network, data=train_images, labels=train_labels)

epoche: 0, loss: 0.0726335934332847
epoche: 1, loss: 0.027260580815447157
epoche: 2, loss: 0.016924282089276453
epoche: 3, loss: 0.014494965411195873
epoche: 4, loss: 0.013200314343305297
epoche: 5, loss: 0.012289596480555899
epoche: 6, loss: 0.01154061271426158
epoche: 7, loss: 0.010922584730813312
epoche: 8, loss: 0.01035358982749609
epoche: 9, loss: 0.009863155723460602


# Accuracy

In [16]:
prediction = network.predict(test_images)
print(sum(prediction == test_labels)/len(test_labels))

0.938


# Save and load

In [22]:
network.save_network('neural_network')

In [32]:
n = Network.load_network('neural_network')

In [30]:
prediction = n.predict(test_images)
print(sum(prediction == test_labels)/len(test_labels))

0.9519


# Network

In [67]:
fully_connected_1 = FullyConnected(out_shape=Shape((15,)), initialization_technique='sigmoid')
activation_layer_sigmoid = ActivationLayer(sigmoid)
fully_connected_2 = FullyConnected(out_shape=Shape((10,)), initialization_technique='softmax') 
activation_layer_soft_max = ActivationLayer(soft_max)
loss_layer = LossLayer(mean_squared_error)
layerlist = [fully_connected_1, activation_layer_sigmoid, fully_connected_2, activation_layer_soft_max, loss_layer]
network = Network(layerlist)

In [43]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [87]:
output = network.forward(train_images, train_labels,unique_length=10)
output

0.11209011367433079

In [70]:
network.tensorlist[2][0].elements

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.33377769e-74,
       4.14081228e-05, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.45260849e-25, 1.00000000e+00,
       1.00000000e+00, 9.99973057e-01, 9.99999372e-01])

In [71]:
network.backprop()

In [74]:
network.tensorlist[1][0].elements

array([  27.69562386,  171.75035953,  313.72672599, -170.10328159,
        -10.09199209,   87.46834609,   94.59948139,  154.94512526,
        181.95918689,  251.6944964 ,  -56.3254973 ,  199.59030414,
        181.73033401,   10.52174898,   14.28127379])

In [86]:
for i in network.layers[0].weights.deltas:
    if np.max(i) > 0:
        print(i)

[ 1.65874242e-14  0.00000000e+00  0.00000000e+00 -4.16890222e-77
  3.36041250e-07  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  1.61056219e-27  0.00000000e+00
  0.00000000e+00  8.18070301e-07  3.02447427e-09]
[ 9.95245452e-14  0.00000000e+00  0.00000000e+00 -2.50134133e-76
  2.01624750e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  9.66337314e-27  0.00000000e+00
  0.00000000e+00  4.90842181e-06  1.81468456e-08]
[ 9.95245452e-14  0.00000000e+00  0.00000000e+00 -2.50134133e-76
  2.01624750e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  9.66337314e-27  0.00000000e+00
  0.00000000e+00  4.90842181e-06  1.81468456e-08]
[ 9.95245452e-14  0.00000000e+00  0.00000000e+00 -2.50134133e-76
  2.01624750e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  9.66337314e-27  0.00000000e+00
  0.00000000e+00  4.90842181e-06  1.81468456e-08]
[ 6.96671817e-13  0.

# Input Layer

In [ ]:
input_layer = InputLayer()
input_tensorlist = input_layer.forward(train_images)

# Fully Connected 1

In [ ]:
out_shape=(100,)
fully_connected = FullyConnected(out_shape=out_shape)
out_tensor_fully_connected1 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=input_tensorlist, out_tensors=out_tensor_fully_connected1)

In [ ]:
out_tensor_fully_connected1[0].elements

array([13855.32327516, 14567.87946531, 12531.64266387, 13065.09199568,
       13717.27042773, 13144.85267195, 14172.86492735, 13344.64554154,
       13789.30046119, 13234.91262216, 14386.86711745, 14110.44445943,
       14011.03393467, 13626.79211007, 14183.92327854, 13196.15787959,
       12533.8216709 , 14009.36439561, 14305.71061599, 14244.94249371,
       13756.82421686, 14248.35678187, 13694.60728455, 13465.37950326,
       13765.26222772, 14410.22192256, 13453.50571786, 13971.10785787,
       13484.35685788, 12655.63794863, 12429.55267367, 14555.04290196,
       13832.72866545, 14343.43362097, 13755.93510764, 13823.52715719,
       13342.75422834, 12687.45679859, 13605.87063681, 13682.76244315,
       13272.07845833, 12832.37884452, 14254.27618778, 12977.85169336,
       15051.38516363, 14307.03311969, 14245.05595451, 12788.95005566,
       13792.19609532, 13385.96231409, 13881.2569936 , 13664.41136983,
       14123.34368646, 13645.73949912, 14719.56784325, 13915.15399392,
      

# Sigmoid

In [ ]:
activation_layer = ActivationLayer(sigmoid)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected1, out_tensor_activation)

In [ ]:
sigmoid_layer = ActivationLayer(sigmoid)

In [ ]:
in_tensors = [Tensor(elements=np.array([1, 2, 3, 4], dtype=np.float64))]
out_tensors = [Tensor(elements=np.array([0, 0, 0, 0], dtype=np.float64))]
out_tensors[0].deltas = np.array([6, 7, 8, 9])
expected_output = [1.1796716, 0.7349551, 0.36141328, 0.15896436]

sigmoid_layer.forward(in_tensors, out_tensors)
sigmoid_layer.backward(out_tensors, in_tensors)

In [ ]:
in_tensors[0].deltas

array([1.1796716 , 0.7349551 , 0.36141328, 0.15896436])

# Fully Connected 2

In [ ]:
out_shape=(10,)
fully_connected = FullyConnected(out_shape=out_shape)
out_tensor_fully_connected2 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=out_tensor_activation, out_tensors=out_tensor_fully_connected2)

In [ ]:
out_tensor_fully_connected2[0].elements

array([21.53422881, 23.77821393, 21.3411817 , 23.2444338 , 22.3820653 ,
       20.77149952, 22.49382576, 19.6519166 , 23.03132047, 19.78697478])

# Soft Max

In [ ]:
activation_layer = ActivationLayer(soft_max)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected2, out_tensor_activation)

In [ ]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[0].elements

10


array([0.03704778, 0.34939171, 0.03054379, 0.20487777, 0.08649141,
       0.01727878, 0.09671858, 0.00564007, 0.16555446, 0.00645564])

# Mean Squared Error

In [ ]:
mse_layer = LossLayer(mean_squared_error)
cross_entropy_layer = LossLayer(loss=cross_entropy)
pred = [Tensor(elements=np.array([0.1, 0.2, 0.3, 0.4], dtype=np.float64))]
target = [Tensor(elements=np.array([1, 0, 0, 0], dtype=np.float64))]
mse = mse_layer.forward(targets=target, predictions=pred)
cross_entropy_val = cross_entropy_layer.forward(targets=target, predictions=pred)

In [ ]:
cross_entropy_val

2.3025850929940455