In [4]:
%load_ext autoreload
%autoreload 2

In [16]:
from src.pnn.layer.input_layer import InputLayer
from src.pnn.tensor import Tensor
from src.pnn.layer.fully_connected import FullyConnected
from src.pnn.layer.activation import ActivationLayer, sigmoid, soft_max
from src.pnn.losses import mean_squared_error
from src.pnn.network import Network
import mnist
import numpy as np 

In [17]:
images = mnist.train_images()

In [18]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()

test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Network

In [19]:
fully_connected_1 = FullyConnected(out_shape=(100,))
activation_layer_sigmoid = ActivationLayer(sigmoid)
fully_connected_2 = FullyConnected(out_shape=(10,)) 
activation_layer_soft_max = ActivationLayer(soft_max)
layerlist = [fully_connected_1, activation_layer_sigmoid, fully_connected_2, activation_layer_soft_max]
network = Network(layerlist)

In [34]:
output = network.forward(train_images)

In [49]:
output[2].elements

array([0.32247967, 0.0279122 , 0.23515256, 0.00772161, 0.00353962,
       0.34620971, 0.01407017, 0.00379568, 0.03313806, 0.00598073])

In [44]:
for i in range(len(output)):
    if round(sum(output[i].elements)) != 1.0:
        print(sum(output[i].elements))

In [47]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# Input Layer

In [4]:
input_layer = InputLayer()
input_tensorlist = input_layer.forward(train_images)

# Fully Connected 1

In [5]:
out_shape=(100,)
fully_connected = FullyConnected(in_shape=input_tensorlist[0].shape, out_shape=out_shape)
out_tensor_fully_connected1 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=input_tensorlist, out_tensors=out_tensor_fully_connected1)

In [6]:
out_tensor_fully_connected1[0].elements

array([13508.72098134, 13967.47235958, 12891.76843827, 13559.41034941,
       13418.1134926 , 13899.85378432, 14400.53736498, 14194.46904883,
       14868.9114156 , 12899.80464552, 13259.11787762, 14343.15875237,
       13323.32575111, 13818.54856543, 13980.41048124, 14660.41131095,
       13801.25906233, 13600.21275362, 14025.25606226, 13464.72161719,
       15131.72595257, 13694.38557782, 14117.9110077 , 14742.16490946,
       13502.78931756, 12587.89353454, 14553.63896289, 13283.73739525,
       14380.62785525, 13527.83522674, 13354.35346448, 14740.94975425,
       12413.74139599, 14001.51509708, 14152.96230703, 13269.12453681,
       13095.84142013, 13643.96379513, 13465.05501938, 15323.61014039,
       13372.41951657, 15108.19755919, 14013.01390166, 14751.45337751,
       13785.72305912, 12147.61668837, 14033.74387727, 13682.24331765,
       14749.37564399, 12520.99288089, 12193.23060741, 13330.73454038,
       13681.73577464, 13857.25580622, 15039.99327574, 12308.50667211,
      

# Sigmoid

In [7]:
activation_layer = ActivationLayer(sigmoid)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected1, out_tensor_activation)

In [8]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[1].elements

100


array([0.8405994 , 0.12505484, 0.95988509, 0.17798985, 0.47540882,
       0.62778221, 0.73908771, 0.46548945, 0.09912268, 0.64038511,
       0.39850173, 0.03833022, 0.18474362, 0.90532862, 0.54702116,
       0.75481104, 0.87260695, 0.57710625, 0.09481868, 0.52213121,
       0.1076132 , 0.8557017 , 0.49285399, 0.49949457, 0.71893696,
       0.88888328, 0.42748435, 0.61362378, 0.6933513 , 0.95542516,
       0.07387227, 0.72527326, 0.97608855, 0.05622198, 0.34561095,
       0.3316632 , 0.61539846, 0.30292053, 0.46823986, 0.19484395,
       0.98386855, 0.28111616, 0.2826545 , 0.08427531, 0.34829627,
       0.41908136, 0.65082668, 0.92400108, 0.82926065, 0.26943009,
       0.1603504 , 0.16996517, 0.62480208, 0.02674944, 0.99661946,
       0.53703089, 0.73023159, 0.06005371, 0.69633204, 0.14688384,
       0.75663797, 0.31557751, 0.29259599, 0.14243612, 0.82158244,
       0.95931125, 0.41306507, 0.7521552 , 0.20418037, 0.73267079,
       0.10756986, 0.38794696, 0.05157972, 0.70531454, 0.28806

# Fully Connected 2

In [9]:
out_shape=(10,)
fully_connected = FullyConnected(in_shape=out_tensor_activation[0].shape, out_shape=out_shape)
out_tensor_fully_connected2 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=out_tensor_activation, out_tensors=out_tensor_fully_connected2)

In [10]:
out_tensor_fully_connected2[0].elements

array([29.26656844, 24.38841452, 24.59375486, 28.99290293, 22.42823978,
       29.13196211, 25.39652565, 22.36149338, 25.0368257 , 23.75257423])

# Soft Max

In [11]:
#summe = [np.exp(x_j) for x_j in out_tensor_fully_connected2[0].elements]
summe = np.sum(np.exp(out_tensor_fully_connected2[0].elements))
summe

13821816723145.932

In [12]:
activation_layer = ActivationLayer(soft_max)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected2, out_tensor_activation)

In [13]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[0].elements

10


array([0.42594416, 0.4496701 , 0.19685133, 0.31389363, 0.93194892,
       0.55543645, 0.29630798, 0.56869974, 0.41107898, 0.93905759])

# Mean Squared Error

In [14]:
prediction = np.array([out_tensor_activation[i].elements.argmax(axis=0) for i in range(len(out_tensor_activation))])

In [16]:
mean_squared_error(train_labels, prediction=prediction)

499762.0