In [6]:
%load_ext autoreload
%autoreload 2

In [7]:
from src.pnn.layer.input_layer import InputLayer
from src.pnn.tensor import Tensor
from src.pnn.layer.fully_connected import FullyConnected
from src.pnn.layer.activation import ActivationLayer, sigmoid, soft_max
from src.pnn.layer.loss import LossLayer, mean_squared_error, cross_entropy
from src.pnn.network import Network
import mnist
import numpy as np 

In [5]:
images = mnist.train_images()

In [6]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()

test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Network

In [5]:
fully_connected_1 = FullyConnected(out_shape=(100,))
activation_layer_sigmoid = ActivationLayer(sigmoid)
fully_connected_2 = FullyConnected(out_shape=(10,)) 
activation_layer_soft_max = ActivationLayer(soft_max)
layerlist = [fully_connected_1, activation_layer_sigmoid, fully_connected_2, activation_layer_soft_max]
network = Network(layerlist)

In [6]:
output = network.forward(train_images)

In [7]:
output[2].elements

array([0.02660059, 0.02174547, 0.1471829 , 0.10153397, 0.0116787 ,
       0.16301947, 0.16059602, 0.24134091, 0.04321697, 0.08308502])

In [8]:
for i in range(len(output)):
    if round(sum(output[i].elements)) != 1.0:
        print(sum(output[i].elements))

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# Input Layer

In [40]:
input_layer = InputLayer()
input_tensorlist = input_layer.forward(train_images)

# Fully Connected 1

In [42]:
out_shape=(100,)
fully_connected = FullyConnected(out_shape=out_shape)
out_tensor_fully_connected1 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=input_tensorlist, out_tensors=out_tensor_fully_connected1)

In [43]:
out_tensor_fully_connected1[0].elements

array([13855.32327516, 14567.87946531, 12531.64266387, 13065.09199568,
       13717.27042773, 13144.85267195, 14172.86492735, 13344.64554154,
       13789.30046119, 13234.91262216, 14386.86711745, 14110.44445943,
       14011.03393467, 13626.79211007, 14183.92327854, 13196.15787959,
       12533.8216709 , 14009.36439561, 14305.71061599, 14244.94249371,
       13756.82421686, 14248.35678187, 13694.60728455, 13465.37950326,
       13765.26222772, 14410.22192256, 13453.50571786, 13971.10785787,
       13484.35685788, 12655.63794863, 12429.55267367, 14555.04290196,
       13832.72866545, 14343.43362097, 13755.93510764, 13823.52715719,
       13342.75422834, 12687.45679859, 13605.87063681, 13682.76244315,
       13272.07845833, 12832.37884452, 14254.27618778, 12977.85169336,
       15051.38516363, 14307.03311969, 14245.05595451, 12788.95005566,
       13792.19609532, 13385.96231409, 13881.2569936 , 13664.41136983,
       14123.34368646, 13645.73949912, 14719.56784325, 13915.15399392,
      

# Sigmoid

In [44]:
activation_layer = ActivationLayer(sigmoid)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected1, out_tensor_activation)

In [45]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[1].elements

100


array([0.07395514, 0.95864078, 0.64536314, 0.51211574, 0.47785172,
       0.31821528, 0.34794268, 0.15299808, 0.78603194, 0.84844911,
       0.11826118, 0.79070264, 0.28315033, 0.19537571, 0.61722834,
       0.09934002, 0.90206985, 0.75291555, 0.08175249, 0.78833471,
       0.59271155, 0.31361596, 0.89771798, 0.09477379, 0.33979575,
       0.40523979, 0.19789784, 0.69982395, 0.73477179, 0.96308922,
       0.73533132, 0.05105152, 0.74393334, 0.37622458, 0.76738324,
       0.67851431, 0.50972801, 0.72720033, 0.35243003, 0.86165675,
       0.66767748, 0.7875432 , 0.08416057, 0.19469414, 0.768648  ,
       0.3909244 , 0.10469516, 0.02093761, 0.40423712, 0.26620896,
       0.31830764, 0.7732067 , 0.78606706, 0.99508372, 0.607022  ,
       0.89770199, 0.07863923, 0.45234224, 0.13126233, 0.16551187,
       0.89628478, 0.30589692, 0.75181766, 0.40440015, 0.07500645,
       0.55389873, 0.35865877, 0.90672263, 0.92001024, 0.27843423,
       0.93131223, 0.63580146, 0.78609617, 0.82298145, 0.49636

# Fully Connected 2

In [47]:
out_shape=(10,)
fully_connected = FullyConnected(out_shape=out_shape)
out_tensor_fully_connected2 = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
fully_connected.forward(in_tensors=out_tensor_activation, out_tensors=out_tensor_fully_connected2)

In [48]:
out_tensor_fully_connected2[0].elements

array([21.53422881, 23.77821393, 21.3411817 , 23.2444338 , 22.3820653 ,
       20.77149952, 22.49382576, 19.6519166 , 23.03132047, 19.78697478])

# Soft Max

In [49]:
#summe = [np.exp(x_j) for x_j in out_tensor_fully_connected2[0].elements]
summe = np.sum(np.exp(out_tensor_fully_connected2[0].elements))
summe

60734365609.874344

In [54]:
activation_layer = ActivationLayer(soft_max)
out_tensor_activation = np.array([Tensor(np.random.rand(out_shape[0]), None) for j in range(0, len(input_tensorlist))])
activation_layer.forward(out_tensor_fully_connected2, out_tensor_activation)

In [55]:
print(len(out_tensor_activation[0].elements))
out_tensor_activation[0].elements

10


array([0.03704778, 0.34939171, 0.03054379, 0.20487777, 0.08649141,
       0.01727878, 0.09671858, 0.00564007, 0.16555446, 0.00645564])

# Mean Squared Error

In [23]:
from src.pnn.layer.loss import LossLayer, mean_squared_error, cross_entropy

In [27]:
mse_layer = LossLayer(mean_squared_error)
cross_entropy_layer = LossLayer(loss=cross_entropy)
pred = [Tensor(elements=np.array([0.1, 0.2, 0.3, 0.4], dtype=np.float64))]
target = [Tensor(elements=np.array([1, 0, 0, 0], dtype=np.float64))]
mse = mse_layer.forward(targets=target, predictions=pred)
cross_entropy_val = cross_entropy_layer.forward(targets=target, predictions=pred)

In [28]:
cross_entropy_val

2.3025850929940455

In [98]:
arr1 = np.array([0.1, 0.2, 0.3, 0.4])
arr2 = np.array([1, 0, 0, 0])

In [90]:
np.power(arr1 - arr2, 2) 

array([0.81, 0.04, 0.09, 0.16])

0.16000000000000003

In [1]:
# Step 1: Define a function
def example_function(x):
    return x * x

# Step 2: Create a class that accepts a function as an argument
class MyClass:
    def __init__(self, func):
        # Store the function in an instance variable
        self.func = func

    def call_function(self, x):
        # Call the stored function and return its result
        return self.func(x)

# Step 3: Create an instance of MyClass, passing the example_function
my_instance = MyClass(example_function)

# Test calling the function through the class instance
print(my_instance.call_function(5))  # Output will be 25
print(my_instance.call_function(10)) # Output will be 100

# example_function remains callable on its own
print(example_function(3))           # Output will be 9


25
100
9


In [2]:
my_instance.func

<function __main__.example_function(x)>